name = "smolpaws"
main = "src/index.ts"
compatibility_date = "2026-02-08"

[[routes]]
pattern = "smolpaws.liberty-labs.org"
custom_domain = true

[[queues.producers]]
queue = "smolpaws-queue"
binding = "SMOLPAWS_QUEUE"

[[queues.consumers]]
queue = "smolpaws-queue"
max_batch_size = 1
max_batch_timeout = 5

[triggers]
crons = ["* * * * *"]

[vars]
ALLOWED_ACTORS = "amanape,neubig,enyst,mamoodi,malhotra5,rbren,xingyaoww"
